### ISSUE TITLE
Latex in WSL2 dont get colorized

### ISSUE THREAD

**Issue by edurojasr** [CoenraadS/Bracket-Pair-Colorizer-2#302]
Hi All
First thanks for this extension!

I want to point out that when using Latex from WLS2, the brackets are not colored.

I've seen that other languages are colored when using WSL2.

I've noticed the following behavior:
1. When you have or open a .tex document with WSL2 the brackets are NOT colored.
2. When using the same .tex file, if I change the language mode in VS Code within the WSL2 to any other one for example to xml, I see that my file does be colored.
3. When you change the language mode back to Latex or Tex, the brackets remain colored.
4. If you opened another .tex file it is no longer colored.

I suspect it will have to do with detecting the language mode in VS Code in WSL2, despite that the language its automatically recognize as tex or latex, the brackets are not being colored, until you manually change the language mode in vs code to another language that does color the brackets and when you return to the latex or tex language mode these colored remain until you change files.

**Comment by iwishiwasaneagle** [comment]
So this doesn't seem to be a WSL2 issue, but rather related to which latex "definition" you have installed. I'm using [LaTex-Workshop](https://github.com/James-Yu/LaTeX-Workshop), however I installed a few other LaTex extensions early on. 

If you look at screenshot 1, you'll notice it actually says the file type is "tex" which threw me as `LaTex-Workshop` doesn't define the file extension ".tex" as `tex` but rather `latex` (see screenshot 2). I dug around the `LaTex-Workshop` configs to see if this was a priority issue or something. However, once looking in `~/.vscode/extensions` I noticed the above - multiple latex extensions. Running `rg "id": "latex"` to find the other definitions, there were 4 other extension defining latex. The final screenshot is where the issue lies, I believe. No configurations in terms of brackets or such is given and upon deleting the "contributes" json section, the `LaTex-Workshop` definition works beautifully with WSL2.

From screenshot 4, you can see WSL2 in action on my `main.tex`. This is on a completely freshly reopened VSCode instance.

![image](https://user-images.githubusercontent.com/12383029/103286276-d8430800-49d7-11eb-80bf-cdb7b40e24e0.png)
![image](https://user-images.githubusercontent.com/12383029/103286676-a67e7100-49d8-11eb-910a-3425ecb453b6.png)
![image](https://user-images.githubusercontent.com/12383029/103287260-fa3d8a00-49d9-11eb-8c7a-25ba18cb661a.png)

![image](https://user-images.githubusercontent.com/12383029/103287791-4ccb7600-49db-11eb-9475-ee091c734a01.png)

**Comment by edurojasr** [comment]
Thanks @iwishiwasaneagle I see the problem now! :)
